name: 'dev_build'
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
        type: string
      is_prerelease:
        description: 'is Pre-release?'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: actions/checkout@v3
      - name: Build artifacts
        run: ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs