name: 'dev_build'
on:
  push:
    paths:
      - 'version.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Build artifacts
        run: ./gradlew build
      - uses: actions/upload-artifact@v3
          with:
            name: Package
            path: build/libs