name: 'dev_build'
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
        type: string
      is_prerelease:
        description: 'is Pre-release?'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ['7.2', '7.4', '7.10', '8.0', '8.3-15w14a', '8.9', '9.4', '10.2', '11.2', '12.2', '13.2', '14.4', '15.2', '16.0-20w14infinite', '16.1', '16.5', '17.0', '17.1', '18.2', '18.2-22w13oneblockatatime', '19.2']
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'


      - name: Checkout 1.${{ matrix.branch }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 1.${{ matrix.branch }}
      - name: Make gradlew executable - 1.${{ matrix.branch }}
        run: chmod +x ./gradlew
      - name: Build artifacts - 1.${{ matrix.branch }}
        run: ./gradlew build


      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs/*.jar
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          path: build/results
      - name: Publish release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: '${{ inputs.release_version }}'
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: ${{ inputs.is_prerelease }}
          title: ${{ inputs.release_version }}
          files: |
            LICENSE*
            build/results/*.jar